import React from 'react';

const quoteSources = { reference: [
  "The great misfortune of the historian is that he cannot observe his facts directly.",
  "There is no good history without the sympathy that springs from a kind of intellectual love.",
  "The historian is, by definition, absolutely incapable of observing the facts which he examines.",
  "The document is mute unless the historian knows how to question it.",
  "Misunderstanding the men of the past is the inevitable fate of those who base their ideas about humanity on their own time alone.",
  "The past is, by definition, a datum which we know only through its relics.",
  "The historian’s task is to make the dead speak.",
  "Historical phenomena never repeat themselves exactly, but they are sufficiently alike to be comparable.",
  "To misunderstand the present is the inevitable consequence of ignorance of the past.",
  "The most important problem of historical knowledge is that of time.",
  "We have seen that the goal of civilization is sedentary culture and luxury.",
  "Injustice ruins civilization. It ruins the human species in that civilization.",
  "The strength of the dynasty rests on the solidarity of the group.",
  "Luxury wears out the dynasty.",
  "When a nation becomes senile, its customs are corrupted.",
  "The foundation of royal authority is reasonable policy and administrative ability.",
  "Taxation may be increased or decreased according to the need for it, but it should never be excessive.",
  "Group feeling is the secret of power.",
  "All human beings, by nature, desire to be led and controlled by a superior.",
  "All dynasties of wide power and extensive royal authority must have religious coloring.",
  "The sciences grow when civilization grows, and decrease when it decreases.",
  "The crafts of the desert are closer to the natural way.",
  "The purpose of royal authority is to make it possible for the people to acquire the goods they need.",
  "It should be known that at the beginning of the dynasty, taxation yields a large revenue from small assessments.",
  "The Bedouins are the basis of civilization, because they are the least dependent on the necessities of life.",
  "Thousands of tired, nerve-shaken, over-civilized people are beginning to find out that going to the mountains is going home.",
  "Awakening from the stupefying effects of the vice of over-industry, they are trying as best they can to mix and enrich their own little ongoings with those of Nature.",
  "In the noblest forests of the world, the ground, once divinely beautiful, is desolate and repulsive, like a face ravaged by disease.",
  "The gardens of the Sierra, also, and the noble forests in both the reserved and unreserved portions are sadly hacked and trampled.",
  "Most of the wild plant wealth of the East also has vanished, — gone into dusty history.",
  "White water-lilies, with rootstocks deep and safe in mud, still send up every summer a Milky Way of starry, fragrant flowers around a thousand lakes.",
  "The notary, using a careful Latin, recorded that four cows and a plough were left behind in the ashes.",
  "Even in the midst of farmers’ fields, precious sphagnum bogs, too soft for the feet of cattle, are preserved with their charming plants unchanged.",
  "The rivers are growing longer, like healthy trees, gaining new branches and lakes as the residual glaciers at their highest sources recede.",
  "The most extensive, least spoiled, and most unspoilable of the gardens of the continent are the vast tundras of Alaska.",
  "Not only are there whales in abundance along the shores, and innumerable seals, walruses, and white bears, but on the tundras great herds of fat reindeer and wild sheep.",
  "In summer they extend smooth, even, undulating, continuous beds of flowers and leaves from about lat. 62° to the shores of the Arctic Ocean.",
  "A Franciscan friar traveling through the province noted that 'the vineyards are black with rot and sorrow.'",
  "On market days, peasants came down from the hills to trade wool, cheese, and news of skirmishes.",
  "The chronicle states that no snow fell that year, and the river did not freeze.",
  "Hazel Green is a good place quietly to camp and study, to get acquainted with the trees and birds, to drink the reviving water and weather, and to watch the changing lights of the big charmed days.",
  "In calm Indian summer, when the heavy winds are hushed, the vast forests covering hill and dale, rising and falling over the rough topography and vanishing in the distance, seem lifeless.",
  "Beavers are building and mending dams and huts for winter, and storing them with food; bears are studying winter quarters as they stand thoughtful in open spaces.",
  "Elk and deer, assembling on the heights, are considering cold pastures where they will be farthest away from the wolves.",
  "Countless thousands of birds are forming parties and gathering their young about them for flight to the southlands.",
  "A free man revels in a scene like this and time goes by unmeasured.",
  "Frosts occur every month of the year. Nevertheless, the tenderest tourist finds it warm enough in summer.",
  "About eighty-five per cent of the entire area of the park is covered with trees, mostly the indomitable lodge-pole pine.",
  "On the divide between the Tule and Deer Creek a central camp was made, and the mountaineer spent his time in deer-hunting, while with provisions for two or three days I explored the woods.",
  "To make sure, I searched the woods a considerable distance south of the last Deer Creek grove, passed over into the basin of the Kern, and climbed several high points commanding extensive views over the sugar-pine woods.",
  "They opened the mosque at al-Azhar and made it a military barracks and camp for the French soldiers.",
  "He issued a proclamation which was read in Arabic and posted on the walls of the city.",
  "They fired their guns and muskets in the air and made a great noise which terrified the people.",
  "On the following day they came in groups to the market, purchasing goods at whatever price they desired.",
  "The French officer walked in the procession to the tomb of the saint, showing reverence in their own way.",
  "They claimed they had come to protect the rights of the people and to deliver them from the tyranny of the Mamluks.",
  "People gathered in the streets, confused and anxious, not knowing whether to flee or to stay.",
  "They distributed a printed sheet in Arabic declaring their respect for Islam and its Prophet.",
  "The cannon fire echoed through the alleyways of Cairo like thunder from the hills.",
  "When the French soldiers began to enter the houses, many families locked their doors and hid their women.",
  "They forced the people to buy what they did not want and to sell what they did not wish to part with.",
  "One of their leaders stood at the entrance of al-Azhar mosque with a drawn sword, mocking those who entered.",
  "A baker complained that the soldiers took his bread and beat him for asking payment.",
  "At night the city was filled with cries of alarm and the sound of boots on stone.",
  "When the uprising began, they fired from rooftops and alleys, but were soon overwhelmed.",
  "After the fighting, corpses lay in the streets for two days before they were gathered.",
  "A merchant said he would rather burn his shop than serve the occupiers.",
  "In their proclamations, they praised the Prophet and claimed friendship, but their actions brought only fear.",
  "They took the muezzin from his tower and demanded he cease the call to prayer.",
  "A child was struck down for approaching a soldier with a stick.",
  "The French dug trenches in the gardens and posted guards at the bathhouses.",
  "At dawn, women carried water past the bodies of those killed in the riots.",
  "An imam who protested the occupation was taken from his house and not seen again.",
  "They translated a verse of the Qur’an onto their posters, claiming divine support.",
  "Many people stayed indoors for weeks, lighting no lamps and speaking only in whispers.",
  "The French commander rode through the quarter alone, expecting praise, and was met with silence.",
  "Some scribes refused to write for them and instead composed verses of mourning.",
  "The fountains in the square ran dry because the aqueducts were damaged in the shelling.",
  "Mothers taught their children new names for fear they’d be mistaken for rebels.",
  "A cannonball struck the minaret of a mosque during noon prayer, scattering the congregation.",
  "The various forms of commercialized leisure which bulked so large in the late-nineteenth-century city were instruments of class formation, and the class so constructed was the petite bourgeoisie.",
  "Popular culture was produced for an audience of petit-bourgeois consumers; a fiction of working-class ways of being was put in place alongside a parody of middle-class style.",
  "Leisure was a performance, Veblen said, and the thing performed was class.",
  "Manet’s Bar almost makes one want to go there, one of these evenings, in order to understand the truth of the room’s reflection in the mirror on the spot, in front of nature.",
  "The woman is firmly established, with a natural movement which is a little brutal. The foreground is taken up by still lifes, magisterially handled." ,
  "To call someone vulgar is to say he insists on a status which is not yet proved or well understood by him, not yet possessed as a matter of form.",
  "The mirror must repeat the picture’s literal surface: it must be the same surface, only farther back. The thing it must not do is act on the matters of visual fact it shows; it must not do things to them.",
  "It is a picture of a woman in a café-concert, selling drinks and oranges, and most probably for sale herself—or believed to be so by some of her customers.",
  "What is visible in modern life, in other words, is not character but class.",
  "They were the shifters of class society, the connoisseurs of its edges and waste lands.",
  "There are two faces, one produced by the hardness of the face’s edge and the closed look of its mouth and eyes; the other less clearly demarcated, opening out into hair let down.",
  "Sexual identity was nowhere but in the body; and it was not there as a structure or a set of attributes, but had to be figured as interference and excess, a tissue of oddities and inconclusiveness.",
  "The mirror must repeat the picture’s literal surface: it must be the same surface, only farther back. The thing it must not do is act on the matters of visual fact it shows; it must not do things to them.",
  "Manet’s Bar almost makes one want to go there, one of these evenings, in order to understand the truth of the room’s reflection in the mi(prror on the spot, in front of nature.",
  "Olympia, on the other hand, looks out at the viewer in a way which obliges him to imagine a whole fabric of sociality in which this look might make sense and include him.",
  "Painting of the school of Baudelaire, freely executed by a pupil of Goya; the vicious strangeness of the little faubourienne, woman of the night from Paul Niquet’s, from the mysteries of Paris and the nightmares of Edgar Poe.",
  "It is not just looking, that is the point: it is not the simple, embodied gaze of the nude.",
  "To call someone vulgar is to say he insists on a status which is not yet proved or well understood by him, not yet possessed as a matter of form.",
  "The crowd in the café-concert did not exist in nature; it was called into being by the painter’s frame.",
    "It was becoming clear that only the rival of the city-state, the territorial state, rich in land and manpower, would in future be able to meet the expense of modern warfare.",
  "Such bravado was all very well, but the event marked the beginning of a train of disasters for the Peninsula, the logical penalty for its wealth, its position at the epicentre of European politics and, undoubtedly the key factor, the fragility of its sophisticated political structures.",
  "Italy: that extraordinary laboratory for statesmen. The entire nation was preoccupied with politics, every man to his own passion, from the porter in the market-place to the barber in his shop or the artisans in the taverns.",
  "These were days when justice was frequently an absent figure and governments were too new and too insecure to dispense with force and emergency measures. Terror was a means of government.",
  "From the Egyptians, Selim gained much of value. In the first place, the annual tribute, originally modest, grew steadily.",
  "In 1521, he seized Belgrade, the gateway to Hungary; in July, 1522, he laid siege to Rhodes, which fell in December of the same year.",
  "The Turkish conquest of the Balkans was assisted by an extraordinary social revolution. A seignorial society, exploiting the peasants, was surprised by the impact and collapsed of its own accord.",
  "The Turkish cavalry, ranging rapidly far and wide, blocking roads, ruining crops and disrupting economic life, went ahead of the main army and prepared the ground for an easy victory.",
  "Eventually Turkey created, throughout the Balkans, structures within which the peoples of the Peninsula gradually found a place, collaborating with the conqueror and here and there curiously re-creating the patterns of the Byzantine Empire.",
  "The Turkish barrier between Christendom and the Indian Ocean was now completed and consolidated, while at the same time a link was established between the hungry metropolis of Constantinople and an extensive wheat, bean and rice-producing region.",
    "In the countryside, every season, every change in the climate, every shift in the wind, every rise or fall in water levels had its own name and significance.",
  "The state had to keep one eye on the sea at all times, but another fixed on the price of grain.",
  "Mediterranean cities lived not only from their hinterlands but from precarious networks of exchange spanning hostile and unstable distances.",
  "Famine was always nearby, like a guest who might arrive without notice.",
  "The galley fleets were a yearly spectacle, but also a drain on resources few port cities could sustain alone.",
  "Whole stretches of coastline were abandoned to pirates or informal powers that neither Ottoman nor Christian authorities could reliably dislodge.",
  "Trade required constant negotiation, not just between states but between rival towns, merchants, and factions within the same polity.",
  "The rhythms of peasant life, even more than the state calendars, organized the real structure of time.",
  "It was common for three systems of law—local custom, religious authority, and imperial decree—to overlap without resolving the contradictions between them.",
  "The grain routes were arteries not just of food but of news, rumor, and political unrest.",
  "Most Mediterranean societies lived in the shadow of older structures: Roman roads, Arab irrigation, Byzantine walls, and vanished cities whose names still echoed in the valleys.",
  "Armies moved slowly not only because of terrain but because logistics—feeding men and horses—rarely kept pace with ambition.",
  "The rich merchant republics built warehouses before they built churches, and consulates before they secured treaties.",
  "Power shifted not just from war but from marriage, migration, plague, and flood.",
  "Documents were copied and recopied until the ink faded into legend, and still they were cited as binding law.",
    "The sea was a surface of movement, but also of constraint: each voyage calculated against the winds, the currents, the pirates, and the ports that might deny entry.",
  "The passage from one shore to another was not just a matter of miles but of customs, languages, currencies, and faiths.",
  "In the age of Philip II, it was still possible for a coastal town to be known by four names and governed by three lords.",
  "The great trading families kept records that spanned generations; to default on a promise was to damage a memory.",
  "Granaries were as important as garrisons; grain riots more feared than enemy fleets.",
  "The salt trade tied mountain villages to port cities with bonds as firm as any treaty.",
  "To govern was to tax, and to tax was to measure the seasons, the harvest, the mouths fed and unfed.",
  "Religious festivals often marked the only predictable breaks in a laborer's calendar.",
  "Small islands played large roles as relays, depots, prisons, and refuges—their silence as strategic as their location.",
  "There were maps drawn with ink and others with memory: fishermen's charts, pilgrims’ songs, smugglers’ routes.",
  "A single mistral wind could erase a month’s trade, drive ships onto rocks, or bring plague from a foreign shore.",
  "The pace of Mediterranean time was measured less by clocks than by sails raised, harvests gathered, and debts postponed.",
  "One town’s prosperity often meant another’s decline; markets shifted like currents, never wholly still.",
  "The archives of cities grew fat with petitions, oaths, fines, exemptions—paper monuments to daily survival.",
  "Over and again, power tried to consolidate the sea—but it flowed between fingers like sand.",
  "Where the desert met the sea, caravans gave way to galleys, and traders switched from camels to coin.",
  "The countryside was rarely still: mule trains moved grain, herders crossed invisible borders, and fugitives vanished into the folds of hill country.",
  "Even silence was a signal—villages without bells, roads without tolls, markets without rumor were noted as omens.",
  "Rivers were bridges and barriers alike, slow arteries feeding the margins of the world.",
  "In the city squares, the weight of memory pressed through the cobblestones: executions, parades, famines, treaties, all walked the same stones.",
  "Each port was a world, and every ship that entered redrew its horizon.",
  "Sailors carried more than cargo: they brought dialects, superstitions, debts, and rumors.",
  "Markets depended on winds; without them, the silks rotted, the oil turned, and the beans sprouted in their sacks.",
  "The pulse of commerce was not steady—it throbbed, vanished, returned, shifted course.",
  "A fisherman might know more about borders than the emperor who drew them.",
  "Caravans moved like shadows across the steppe, appearing at the edge of vision, then vanishing again.",
  "Stone watchtowers still stood from a time no one remembered, facing the sea as if waiting for someone.",
  "An island could be both prison and sanctuary, depending on the direction of the wind.",
  "The debt ledgers of the spice traders were better maps than the ones painted on vellum.",
  "Even the plagues had itineraries, traced backward from death to ship to contract to port.",
  "To harvest salt or olives or wheat was to join a chain of labor that curved across continents.",
  "A document written in Venice might be enforced in Tunis or ignored in Palermo, depending on who docked first.",
  "Grain weighed more than gold in most seasons.",
  "Fires were both disasters and resets—whole quarters of cities rebuilt in different styles after the ash cooled.",
  "Some languages existed only on ships: a patchwork of curses, weights, and numbers.",
  "Clocks were rare; bells and tides regulated the day.",
  "The silence of empty streets during fasts or funerals told historians more than the proclamations.",
  "A city might burn for a wedding or a riot—it was the crowd that lit it either way.",
  "No treaty lasted longer than the hunger it failed to relieve.",
  "On some nights, a harbor full of anchored ships looked like a marketplace asleep under stars.",
    "The shipwrecks that littered the coastline were charts in negative—routes remembered by their ruin.",
  "Beneath each market square lay the foundations of older stalls, older taxes, older tongues.",
  "The wind carried not just weather but law, blowing decrees from one coast to another, sometimes unread.",
  "A fortress was never truly finished; each generation added stone to someone else’s fear.",
  "Before they were borders, the mountain ranges were stories—retold in footpaths and watchfires.",
  "Every drought rearranged alliances more quickly than diplomacy.",
  "An olive grove could serve as a dowry, a hiding place, a battlefield, or a tomb, depending on the century.",
  "The same well might be blessed in one season and poisoned in another.",
  "Pilgrims and fugitives often walked the same roads, greeted by the same uncertain silence.",
  "The census takers came after the plague, counting ghosts and survivors alike.",
  "In port cities, names changed with the tide—spelled differently in each language that passed through.",
  "Paperwork outlasted kingdoms: promissory notes remained collectible even after thrones had fallen.",
  "Cities grew in rings: walls, then roads, then taxes, then fire.",
  "Ships returned bearing not just goods but weathered prayers, rewritten wills, unclaimed cargo.",
  "It was said the sun touched every flag once a day, but some flags took longer to burn.",
  "A shepherd might know more about empire than any governor, because his paths crossed fewer lies.",
  "The architecture of silence—hidden rooms, false walls, second names—was more intricate than that of palaces.",
  "Storms were named only after they had passed; no one dared mark them in advance.",
  "In every port ledger, a blank line hinted at cargo unlisted, stories untold.",
  "Graves on trade routes were never empty long—they made room for the next traveler.",
  "A broken aqueduct told more about conquest than any monument left standing.",
  "Fishermen timed their voyages not by the moon, but by the taxes due at shore.",
  "The same hill might host a shrine, a watchtower, and a gallows within a hundred years.",
  "Even silence was taxed, if it meant withholding news.",
  "A harbor closed for repairs was enough to reroute history.",
  "Traders learned to fake origins as easily as weights or titles.",
  "A cathedral might rise atop a grain market, but the market would return after vespers.",
  "Messages folded in bread or sewn into seams sometimes arrived decades too late.",
  "The dust in archives was counted among the oldest inhabitants of a city.",
  "No single language could name all the tools found on a merchant ship.",
  "In times of famine, the coin was softer than bread.",
  "A map could lie more convincingly than a witness—it needed only to be printed.",
  "The procession of the dead often passed the same doors as the wedding feasts.",
  "Certain stones in city walls were known to echo, but only in a particular wind.",
  "Some ruins became more useful after their fall: they housed bees, shade, revolution.",
  "Every treaty drafted on land unraveled at sea.",
  "The road between two villages might be measured in stories, not steps.",
  "No oath held longer than the hunger it ignored.",
  "Some bells were rung only in war or eclipse, and no one remembered which came first.",
  "A merchant’s honesty was not judged in speech but in how he wrapped his smallest item.",
  "Flags changed often, but the patterns of tide and salt on stone remained.",
  "The plague never traveled alone—it brought silence, superstition, and rearranged the furniture.",
  "Ink ran quicker during famine; declarations multiplied when bread disappeared.",
  "A torch dropped in a narrow alley rewrote the boundaries of five houses.",
  "What could not be taxed was eventually renamed.",
  "The longest roads were often paved with exemptions.",
  "Some cities had more prisons than fountains, but called both public works.",
  "When clocks arrived, they were placed in towers—far from the hands of those who tilled.",
  "The best smuggler knew both scripture and tide charts.",
  "A harbor’s smell could forecast war before the envoys arrived.",
    "The Mediterranean as a unit, with its creative space, the amazing freedom of its sea-routes... is the unceasing work of human hands; but those hands have had to build with unpromising material, a natural environment far from fertile and often cruel.",
  "All civilization can be defined as a struggle, a creative battle against the odds: the civilizations of the Mediterranean basin have wrestled with many often visible obstacles, using sometimes inadequate human resources.",
  "The volume of traffic in these free ports gives some idea of the lack of success of the Spanish fronteras.",
  "Life in the presidios must have been miserable. So near the water, rations rotted and men died of fever. The soldiers were hungry all year round. For a long time, the only supplies came by sea.",
  "The supply station of Malaga... was responsible for supplying the western sector... All supplies for Africa travelled from here: munitions, rations, construction materials, soldiers, convicts, labourers and prostitutes.",
  "The sea was infested with pirates. So it was only in winter, when pirates were few, that the risk would be taken of sending to Oran... boats placed under embargo, and requisitioned to transport supplies or munitions.",
  "The city had to be open to foreign caravans and ships, to the boats bringing ransom for captives, Christian vessels...",
  "What happened in the great cities like Venice, Naples or Constantinople when plague or famine or war intensified an already furious struggle for existence.",
  "The suspension of major hostilities in the Mediterranean after 1574 was undoubtedly one cause of the subsequent series of political and social disturbances, including the increase in brigandage.",
  "From 1574–1580, it increased its activities even further, soon coming to dominate the now less spectacular history of the Mediterranean.",
  "The new capitals of warfare were not Constantinople, Madrid and Messina, but Algiers, Malta, Leghorn and Pisa.",
  "Privateering required above all things a market for its spoils. Algiers could not become a pirate stronghold without also becoming an active commercial centre.",
  "The transformation had been accomplished. In order to have food and equipment and to sell the prizes of war, the city had to be open to foreign caravans and ships, to the boats bringing ransom for captives, Christian vessels...",
  "The Mediterranean in the sixteenth century was overwhelmingly a world of peasants, of tenant farmers and landowners; crops and harvest were the vital matters of this world and anything else was superstructure, the result of accumulation and of unnatural diversion towards the towns.",
  "Peasants and crops, in other words food supplies and the size of the population, silently determined the destiny of the age.",
  "In both the long and the short term, agricultural life was all-important.",
  "Could it support the burden of increasing population and the luxury of an urban civilization so dazzling that it has blinded us to other things?",
  "The same was true of Castile. Nowadays, historians tell us that material equilibrium was maintained in Castile until the mid-seventeenth century.",
  "This must affect our former assumptions. I had previously supposed that the short but violent crisis of the 1580s could be explained entirely by Spain’s new reorientation towards Portugal and the Atlantic.",
  "This, it seems was too ‘noble’ an explanation. Felipe Ruiz Martin has shown that it was simply the result of a process arising basically from the great grain crisis in the Iberian Peninsula in the 1580s.",
  "The rich and luxurious nobles, sinking into their natural character, accepted, as a favor, this disgraceful exemption from military service; and as long as they were indulged in the enjoyment of their baths, their theatres, and their villas, they cheerfully resigned the more dangerous cares of empire to the rough hands of peasants and soldiers.",
  "The mildness and precision of their laws ascertained the rule and measure of taxation, and protected the subject of every rank against arbitrary interpretations, antiquated claims, and the insolent vexation of the farmers of the revenue.",
  "Avarice and taste very frequently despoiled the vanquished nations of the elegant statues of their gods, and the rich ornaments of their temples.",
  "Rome gradually became the common temple of her subjects; and the freedom of the city was bestowed on all the gods of mankind.",
  "In a great empire like that of Rome, a natural balance of money must have gradually established itself.",
  "We are informed that, by the conquests of Pompey, the tributes of Asia were raised from fifty to one hundred and thirty-five millions of drachms; or about four millions and a half sterling.",
  "Gaul was enriched by rapine, as Egypt was by commerce, and the tributes of those two great provinces have been compared as nearly equal to each other in value.",
  "The ruins of antiquity inspire less wonder than the order and majesty of the imperial institutions they outlived.",
  "The fall of Rome was less a singular catastrophe than the slow crumbling of a massive edifice, burdened by its own grandeur.",
  "The introduction of Christianity, whose primitive purity was soon clouded by superstition, contributed to the internal dissolution of the empire.",
  "The monks, those pale and unmanly recluses, multiplied under every decay of national spirit.",
  "The last emperors of the West, noble in title but feeble in action, served as the ghostly shadows of Roman dominion.",
  "The loss of military discipline preceded the loss of territory; both were the consequences of luxury and indolence.",
  "Religious zeal kindled civil discord, and the name of Christ was invoked to justify fratricide and usurpation.",
  "Among the Goths and Vandals, the discipline of arms and the vigor of uncivilized virtue prevailed against the opulence of the dying empire.",
  "The Roman Senate, once the master of the known world, dwindled to a ceremonial relic, convening for form, not power.",
  "The sublime philosophy of the ancients gave way to the mystical jargon of monkish sophistry.",
  "Rome fell, not to the barbarian alone, but to the corruption within: superstition, despotism, and economic decay.",
  "The Christian hierarchy succeeded the civil magistracy, yet the empire was none the more virtuous for the exchange.",
  "The authority of the bishops waxed as that of the praetors waned, and the cross replaced the eagle on imperial standards.",
  "What was once civic religion became private credulity, and what was once public virtue became cloistered piety.",
  "The temples were abandoned not because they were discredited by reason, but because their splendor was surpassed by the novelty of a rising faith.",
  "The historian must discern in the ashes of greatness not only what was lost, but what replaced it—and with what cost.",
   "Julian endeavored to restore paganism, not as religion, but as cultural resistance against the new ascendency of the Christian priesthood.",
  "The philosophical schools flourished under imperial favor, yet their lofty ideals proved powerless against the mysticism of the age.",
  "Constantine embraced the cross but wielded the sword; the union of throne and altar ensured neither peace nor purity.",
  "In the solemn language of the law, the name of Caesar became less a title than a fragile hope of order amid chaos.",
  "The empire in the East prolonged the form without the strength of Roman rule, a glittering shell bereft of civic spirit.",
  "With the fall of Rome, the memory of law outlived its administration; tradition clung where governance had fled.",
  "Julian's death marked the last Roman effort to stem the Christian tide; what followed was theocratic absolutism clothed in spiritual rhetoric.",
  "Philosophy retired from the world as superstition advanced; the temples of reason stood vacant beneath domes of credulity.",
  "To restore virtue, Julian revived the rites of antiquity—but incense and augury could not revive the old soul of the city.",
   "About early vassalage, based on the group of armed followers gathered round the chief, there was a sort of cosy domestic flavour, which was expressed in its very vocabulary.",
  "Fealty, in short, was based at that time on personal contact and subjection shaded off into comradeship.",
  "The sense of free choice was so far lost that it was no uncommon thing for a vassal to alienate the duties of vassalage along with the fief, and for the lord to give or sell the loyalty of his men along with his fields, his woods, and his castles.",
  "Eventually this fealty, so much sought after, became completely meaningless, and the dependence of one man upon another was soon no more than the concomitant of the dependence of one estate upon another.",
  "The collapse of the Carolingian state represented the swift and tragic defeat of a little group of men who, despite many archaisms and miscalculations but with the best of intentions, had tried to preserve some of the values of an ordered and civilized life.",
  "The peasant of Forez who, as late as 1280, transformed his allod into a villein tenement on condition of being henceforth ‘protected, defended and warranted’... doubtless thought he was doing something to his advantage.",
  "To seek a protector, or to find satisfaction in being one—these things are common to all ages.",
  "In the humble drama of rural life we recognize an aspect of the same development which, at a higher social level, impelled so many men to submit themselves to the ties of vassalage.",
  "The very name of these exactions was significant. They were normally called banalites... their sole foundation was the lord’s acknowledged power to give orders, signified by the old Germanic word ban.",
  "It was better for the lord instead of keeping all the plots of land in his own hands to have permanently at his disposal the labour and resources of dependants who were in a position to maintain themselves.",
  "The splendour of these courts, ‘full, marvellous and great’, has been naively exaggerated by the epic poems... Nevertheless, we know from the most reliable sources that much legal business was dealt with in these assemblies.",
  "The parish church was dependent almost everywhere on the local lord... this right of ownership consisted primarily in the power to nominate or ‘present’ the priest in charge.",
  "The appropriation of tithe by the lords was one of the most striking as well as one of the most profitable achievements of a power which repudiated the right of anyone else to demand anything from its subjects.",
  "Tallage, which had at first been exceptional, was levied at more and more frequent intervals as the circulation of money increased.",
  "Nothing varied more from manor to manor according to locality, nothing exhibited more diversity, than the burdens of tenancy in the first feudal age.",
  "The peasantry’s remarkable capacity for passive resistance and the inefficient management of the manors were the only effective counterbalances to abuse of power.",
  "The charter of customs was a very general institution in the Europe of later feudal times... they were little local constitutions often negotiated with the subjects themselves.",
  "The case of England shows how in a homogeneous civilization, certain ideas shaped by a specific environment could result in a completely original legal system.",
  "In the German manors, dependants were summoned to periodic assemblies, where the lord read aloud the rules governing them—this became the Weistum.",
  "As remuneration for service, the fief had originally redressed the imbalance, but once it became patrimonial property, the inequality of obligations became flagrant.",
  "The primary duty was, by definition, military service. The ‘man of mouth and hands’ was bound, first and foremost, to serve in person, on horseback and with full equipment.",
  "Symbolic acts known as investitures were adopted to mark the transfer of real property rights; a clod of earth or a lance might be used to represent the land or military service.",
  "The act of homage consisted of placing one's joined hands between those of the lord—a plain symbol of submission—followed by a kiss to signify accord.",
  "In the ceremony of breach of homage, a twig or thread was violently thrown down by the vassal in repudiation of his lord.",
  "In the courts held by lords, vassals were required to appear ‘carefully arrayed in accordance with their rank,’ and many legal matters were settled during these ceremonial gatherings.",
  "Feudal relief—the tax on inheritance—required the heir of a military vassal to offer arms or a horse, unlike the cattle handed over by peasant heirs.",
  "In early customs, a vassal’s obligation of military service was limited to forty days, beyond which support or payment was expected from the lord.",
  "The obligation to the overlord could be commuted or reduced by custom, as in the case of the bishop of Bayeux, who sent only a fraction of his knights to his immediate superior.",
  "Primogeniture preserved the indivisibility of greater fiefs in some regions, but in practice, most estates were still divided among heirs.",
  "Over time, lords lost the right to refuse new investitures, and the transfer of fiefs became routine—usually finalized with a formal homage and fee.",
  "The eighth-century world map of Albi shows the Mediterranean as the centre of the world.",
  "One exciting renaissance had taken place in the second century AD. It coincided with a revival of the economic life and the political initiative of the upper classes of the Greek cities.",
  "The history of the Roman empire is the history of the ways in which 10 percent of the population, who lived in the towns, fed themselves from the labours of the remaining 90 percent who worked the land.",
  "Very few of the great cities of the Roman empire could hope to supply their own needs from their immediate environment.",
  "The inland Roman life had always tended to coagulate in little oases, like drops of water on a drying surface.",
  "Classical society of about AD 200 was a society with firm boundaries.",
  "The existence of the ‘barbarian’ exerted a silent, unremitting pressure on the culture of the Roman empire.",
  "Classical culture existed to exclude alternatives to its own world.",
  "By 200, the empire was ruled by an aristocracy of amazingly uniform culture, taste and language.",
  "The Roman empire was one of the very few great states in the ancient world that had so much as attempted to create an oasis of peaceful civilian government among societies that had always lived by war.",
  "The military revolution of the late third century was treated with uncomprehending hostility by the conservative civilians of the time.",
  "A rising current of able men, less burdened by the prejudices of an aristocracy and eager to learn, maintained a tone of vigour and disquietude that distinguishes the intellectual climate of Late Antiquity from any other period of ancient history.",
  "The fourth century is the most prosperous period of Roman rule in Britain.",
  "The new aristocracies were, more often than not, families with strong local roots.",
  "In the later empire, all attempts to secure protection and redress of grievances had to pass through a great man—a patronus—‘the boss’.",
  "The new elites were exceptionally open. The splendid new art of the age is the work of craftsmen and patrons who felt themselves shaken free from the restraints of previous generations.",
  "Men now drew on what lay close to hand. Local craftsmen felt free to bring to life images more rooted in their own traditions.",
  "In the East, monasticism flowed directly into the life of the great cities and strengthened the bishops’ position in urban society.",
  "The monks of Upper Egypt terrorized pagans, ran ambulances, and distributed aid during barbarian invasions.",
  "The church’s wealth by the sixth century rivaled the state’s, and bishops functioned as municipal governors in times of crisis.",
  "A Roman senator might write as if he lived in Augustus’s time and wake to find no emperor ruled in Italy.",
  "Holy men served as brokers of protection and embodied a ‘freedom’ beyond village and empire alike.",
  "To understand the shifts of the fourth century we must retrace not only the politics but the inner habits of Late Antique life."
], fiction: [
  "If it had not rained on a certain May morning her whole life would have been entirely different.",
  "She wakened early, in the lifeless, hopeless hour just preceding dawn. She had not slept very well. One does not sleep well, sometimes, when one is twenty-nine on the morrow, and unmarried, in a community and connection where the unmarried are simply those who have failed to get a man.",
  "They had long since relegated her to hopeless old maidenhood.",
  "But she herself had never quite relinquished a certain pitiful, shamed, little hope that Romance would come her way yet—never, until this wet, horrible morning, when she wakened to the fact that she was twenty-nine and unsought by any man.",
  "Ay, there lay the sting. She did not mind so much being an old maid. After all, she thought, being an old maid couldn’t possibly be as dreadful as being married to an Uncle Wellington or an Uncle Benjamin, or even an Uncle Herbert. What hurt her was that she had never had a chance to be anything but an old maid. No man had ever desired her.",
  "The tears came into her eyes as she lay there alone in the faintly greying darkness. She dared not let herself cry as hard as she wanted to, for two reasons. She was afraid that crying might bring on another attack of that pain around the heart. She had had a spell of it after she had got into bed—rather worse than any she had had yet. And she was afraid her mother would notice her red eyes at breakfast and keep at her with minute, persistent, mosquito-like questions regarding the cause thereof.",
  "“Suppose,” she thought with a ghastly grin, “I answered with the plain truth, ‘I am crying because I cannot get married.’ How horrified Mother would be—though she is ashamed every day of her life of her old maid daughter.”",
  "But of course appearances should be kept up. “It is not,” Valancy could hear her mother’s prim, dictatorial voice asserting, “it is not maidenly to think about men.”",
  "The thought of her mother’s expression made her laugh—for she had a sense of humour nobody in her clan suspected. For that matter, there were a good many things about her that nobody suspected. But presently she lay there, a huddled, futile little figure, listening to the rain pouring down outside and watching, with a sick distaste, the chill, merciless light creeping into her ugly, sordid room.",
  "She knew the ugliness of that room by heart—knew it and hated it. The yellow-painted floor, with one hideous, “hooked” rug by the bed, with a grotesque, “hooked” dog on it, always grinning at her when she awoke; the faded, dark-red paper; the ceiling discoloured by old leaks and crossed by cracks; the narrow, pinched little washstand; the brown-paper lambrequin with purple roses on it; the spotted old looking-glass with the crack across it, propped up on the inadequate dressing-table; the jar of ancient potpourri made by her mother in her mythical honeymoon; the shell-covered box, with one burst corner, which Cousin Stickles had made in her equally mythical girlhood; the beaded pincushion with half its bead fringe gone; the one stiff, yellow chair; the faded old motto, “Gone but not forgotten,” worked in coloured yarns about Great-grand-mother Stirling’s grim old face; the old photographs of ancient relatives long banished from the rooms below.",
  "There were only two pictures that were not of relatives. One, an old chromo of a puppy sitting on a rainy doorstep. That picture always made Valancy unhappy. That forlorn little dog crouched on the doorstep in the driving rain! Why didn’t some one open the door and let him in?",
  "But she never dared destroy it or remove it.",
  "Every room in the house was ugly, of course.",
  "There was no money for rooms nobody ever saw.",
  "Valancy never persisted. She was afraid to.",
  "Her mother could not brook opposition. Mrs. Stirling would sulk for days if offended, with the airs of an insulted duchess.",
  "The only thing Valancy liked about her room was that she could be alone there at night to cry if she wanted to.",
  "But, after all, what did it matter if a room, which you used for nothing except sleeping and dressing in, were ugly?",
  "People who wanted to be alone, so they believed, could only want to be alone for some sinister purpose.",
  "She had lived spiritually in the Blue Castle ever since she could remember. She had been a very tiny child when she found herself possessed of it.",
  "All that supported her through the boredom of her days was the hope of going on a dream spree at night.",
  "Most, if not all, of the family would have died of horror if they had known half the things she did in her Blue Castle.",
  "I don’t say she deliberately murdered these lovers as she outgrew them.",
  "One simply faded away as another came.",
  "Reality pressed on her too hardly, barking at her heels like a maddening little dog.",
  "She was twenty-nine, lonely, undesired, ill-favoured—the only homely girl in a handsome clan, with no past and no future.",
  "As far as she could look back, life was drab and colourless, with not one single crimson or purple spot anywhere. As far as she could look forward it seemed certain to be just the same until she was nothing but a solitary, little withered leaf clinging to a wintry bough.",
  "The moment when a woman realises that she has nothing to live for—neither love, duty, purpose nor hope—holds for her the bitterness of death.",
  "“And I just have to go on living because I can’t stop. I may have to live eighty years,” she thought, in a kind of panic.",
  "“We’re all horribly long-lived. It sickens me to think of it.”",
  "Much as she hated going to the picnic, it would never have occurred to her to rebel against it.",
  "Aunt Alberta, enormously fat, with an amiable habit of always referring to her husband as “he,” as if he were the only male creature in the world, never let you forget that she had been a great beauty in her youth.",
  "She had been poor all her life and knew the galling bitterness of it.",
  "So she endured his riddles and even smiled tortured little smiles over them.",
  "Aunt Isabel prided herself on saying what she thought, but didn’t like it so well when other people said what they thought to her.",
  "She felt vaguely that if she had come across these books years ago life might have been a different thing for her.",
  "They seemed to her to yield glimpses of a world into which she might once have entered, though the door was forever barred to her now.",
  "“Where does he live?” Valancy had asked.",
  "“Nobody knows. From his books he must be a Canadian, but no more information can be had. His publishers won’t say a word. Quite likely John Foster is a nom de plume. His books are so popular we can’t keep them in at all, though I really can’t see what people find in them to rave over.”",
  "“I think they’re wonderful,” she said, timidly.",
  "She could hardly say what it was—some tantalising lure of a mystery never revealed—some hint of a great secret just a little further on—some faint, elusive echo of lovely, forgotten things—his magic was indefinable.",
  "She did not want any one to know about her heart.",
  "She felt that she couldn’t tell anybody unless she had to.",
  "She felt quite sure there was nothing at all seriously wrong with her heart and no need of all the bother that would ensue if she mentioned it.",
  "The doctor was a gruff, outspoken, absent-minded old fellow, but he was a recognised authority on heart disease, even if he were only a general practitioner in out-of-the-world Deerwood.",
  "None of the family had ever gone to him since he had told Cousin Gladys, ten years before, that her neuritis was all imaginary and that she enjoyed it.",
  "You couldn’t patronise a doctor who insulted you like that—not to mention that he was a Presbyterian.",
  "But she, between the devil of disloyalty to clan and the deep sea of fuss and clatter and advice, thought she would take a chance with the devil."
]}




export async function QuoteGetter(arg) {
     try {
        console.log(arg)
    
    const quotes = quoteSources[arg]

    const randomNum = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomNum];
    return { line: randomQuote };
  } catch (err) {
    console.error("Error fetching quotes:", err);
    return { line: null };
  }
}

